name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.23.0'
      - name: Go build for Linux ARM64
        env:
          GOOS: linux
          GOARCH: arm64
        run: |
          go build -o rover-mems-linux-arm64 ./...

      - name: Zip exes
        run: |
          zip -r rover-mems-linux-arm64.zip rover-mems-linux-arm64

      - name: Create draft release if main branch
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create arelease --title "Draft release" --draft --target "${GITHUB_SHA}" --notes "Draft release automatically made from successful main branch build" rover-mems-linux-arm64.zip